baseURL = "https://waaaaall.com/"
languageCode = "ja-jp"
title = ""
description = "description"
theme = "hugo-theme-hello-friend-ng"
absLangURL = "tes"
copyright = "©2022 waaaaall"

# Subtitle for home
homeSubtitle = "A simple and beautiful blog"
defaultTheme = "dark"

[params.author]
  name = "waaaaall"
  homepage = "https://waaaaall.com/"
  mainTwitter = "https://twitter.com/good_wall"
  techTwitter = "https://twitter.com/_waaaaall"

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Profile"
url = "/profile/"
weight = 2
