baseURL = "https://waaaaall.com/"
languageCode = "ja-jp"
title = "…"
theme = "hugo-theme-hello-friend-ng"
defaultContentLanguage = "ja"

# Disable taxonomies
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "loading…"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Author settings
  [params.author]
    name = "waaaaall"
    homepage = "https://waaaaall.com/"
    mainTwitter = "https://twitter.com/good_wall"
    techTwitter = "https://twitter.com/_waaaaall"

[languages]
  [languages.ja]
    title = ""
    subtitle = "loading…"
    keywords = ""
    copyright = "©2025 waaaaall"
    readOtherPosts = "他の記事を読む"
    weight = 1

    [languages.ja.params.logo]
      logoText = " "
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "about"
        name = "…"
        url = "/about"
        weight = 1
