baseURL = "http://waaaaall.com/"
languageCode = "ja-jp"
title = "waaaaallib"
author = "waaaaall"
description = "description"
theme = "hugo-theme-hello-friend-ng"

# Subtitle for home
homeSubtitle = "A simple and beautiful blog"
defaultTheme = "dark"

disableKinds = ["taxonomy", "taxonomyTerm"]
